// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const FALLBACK_URL = "https://gqnjtibpyjunmgvaapdp.supabase.co";
const FALLBACK_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdxbmp0aWJweWp1bm1ndmFhcGRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxODUxNjEsImV4cCI6MjA3MTc2MTE2MX0.E6fpdrBcn12hpDtV9AD3JYmJA674qknhKHlCOUbzviI";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || FALLBACK_URL;
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY || FALLBACK_KEY;

// Export constants for use in other components
export { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY };

// Function to check if Supabase is configured
export const isSupabaseConfigured = () => {
  return !!(
    SUPABASE_URL !== FALLBACK_URL && SUPABASE_PUBLISHABLE_KEY !== FALLBACK_KEY
  );
};

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
